select *from employee
select*from employee where empname like 's%'
select*from employee where empname like 'a%'
select*from employee where empname like '%n'
select*from employee where empname not like 's%'
select*from employee where empname not like '%s'
select*from employee where empname not like '%s%'
select*from employee where empname  like '%s%'
select*from employee where empname  like '[a,s,r]%'
select*from employee where empname not like '[a,s,r]%'
select*from employee where empname  like '%[a,s,r]'
select*from employee where empname  not like '%[a,s,r]'
select*from employee where empname  like '%[a,s,r]%'
select*from employee where empname  like '[a-e]%'
select*from employee where empname  like '%[a-e]'
select*from employee where empname not like '[a-e]%'
select*from employee where empname  like 'a___'
select*from employee where empname  like 's_____'
select*from employee where empname  like 's____'
select*from employee where empname not like 'a___'